[project]
authors = ["Alex Nagorny <alex@swaygang.com>"]
entry = "main.sw"
license = "Apache-2.0"
name = "token"

[dependencies]
asset = { git = "https://github.com/FuelLabs/sway-libs"}
src20 = { git = "https://github.com/FuelLabs/sway-standards" }
src3 = { git = "https://github.com/FuelLabs/sway-standards" }
